
server:
  port: 8080


#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
    register-with-eureka: true
    healthcheck:
      enabled:  false
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-product
          uri: lb://ms-product
          predicates:
            - Path=/api/products/**
        - id: ms-customer_full
          uri: lb://ms-customer
          predicates:
            - Path=/ms-customer/v1/api/customer/full/**
          filters:
            - name: AuthenticationFiltering
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/ms-customer/v1/api/customer/**
        - id: ms-transactions_add
          uri: lb://ms-transactions
          predicates:
            - Path=/api/transactions/add/**
            - Method=POST
          filters:
            - name: AuthenticationFiltering
        - id: ms-transactions
          uri: lb://ms-transactions
          predicates:
            - Path=/api/transactions/**
          # filters:
          #   - name: AuthenticationFiltering
        - id: mc-api-add
          uri: lb://mc-api
          predicates:
            - Path=/mc-api/v1/api/external-product/**
            - Method=POST
          filters:
            - name: AuthenticationFiltering
        - id: mc-api
          uri: lb://mc-api
          predicates:
            - Path=/mc-api/v1/api/external-product/**